name: build

on:
  push:
    branches:
      - main
      - 'renovate/**'

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        distro: [focal, bionic]
        arch: [x86_64]

    env:
      DISTRO: ${{ matrix.distro }} # build target, name required by binary-builder
      ARCH: ${{ matrix.arch }} # build target, name required by binary-builder

    steps:
      - uses: actions/checkout@v2.3.4

      - name: docker-config
        uses: renovatebot/internal-tools@v1.5.0
        with:
          command: docker-config

      - name: binary-builder
        uses: renovatebot/internal-tools@v1.5.0
        with:
          command: binary-builder
          dry-run: ${{github.ref != 'refs/heads/main'}}
          build-args: DISTRO,ARCH
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v2.2.2
        with:
          name: ${{ env.DISTRO }}
          path: .cache/*.tar.xz
